learning_users/basic_app/urls.py
from django.urls import path
from . import views

# TEMPLATE URLS
app_name='basic_app'

urlpatterns=[
    path('',views.basic_app_index,name='basic_app_index'),
    path('register/',views.register,name='register'),  # name is required.
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'), # name is required
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name="special"),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required()
def special(request):
    return HttpResponse("You are logged in, nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered=False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()


    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def basic_app_index(request):
    return render(request,'basic_app/basic_app_index.html')

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Login failed")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style>

img{
  width: 500px;
  margin:20px auto;
  display:block;
}

#copyright{
  text-align: center;
}


</style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <div class="container">

        <a class="navbar-brand" href="{%url 'index'%}">DJANGO</a></li>

        <button class="navbar-toggler" type="button" name="button" data-toggle="collapse" data-target="#collapsecontent" aria-controls="collapsecontent" aria-expanded="false" aria-label="Toggle navigation">

           <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse" id="collapsecontent">

          <ul class="navbar-nav mr-auto">

              <li class="nav-item active"><a class="nav-link" href="{%url 'basic_app:basic_app_index'%}">소개</a></li>
              <li class="nav-item active"><a class="nav-link" href="{%url 'basic_app:register'%}">등록</a></li>

            {%if user.is_authenticated%}

              <li class="nav-item active"><a class="nav-link" href="{%url 'logout'%}">로그아웃</a></li>

            {%else%}

              <li class="nav-item active"><a class="nav-link" href="{%url 'basic_app:user_login'%}">로그인</a></li>

            {%endif%}

              <li class="nav-item"><a class="nav-link" href="{%url 'admin:index'%}">관리자</a></li>

          </ul>

          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="검색" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
          </form> -->

        </div>

      </div>

    </nav>

    <div class="container">

      {%block body_block%}

      {%endblock%}

    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

learning_users/templates/basic_app/basic_app_index.html
{%extends 'base.html'%}
{%load static%}
{%block body_block%}

  <div class="jumbotron">

    <h1>소개</h1>

  </div>

  <img src="{%static 'img2.jpg'%}" alt="Photo by Christopher Rusev on Unsplash">
  <p id="copyright">Photo by Christopher Rusev on Unsplash</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{%endblock%}

learning_users/templates/basic_app/index.html
{%extends 'base.html'%}
{%load static%}
{%block body_block%}

<style>


</style>

  <div class="jumbotron">

    <h1>Django 튜토리얼 홈페이지</h1>

  </div>

  <img src="{% static "img.jpg" %}" alt="Sunrise hiking views">

  <p id="copyright">Photo by Mukuko Studio on Unsplash</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{%endblock%}

learning_users/templates/basic_app/login.html
{%extends 'base.html'%}
{%block body_block%}

  <div class="jumbotron">

    <h1>로그인 해주세요</h1>

    <form action="{%url 'basic_app:user_login'%}" method="post">

      {%csrf_token%}
      <label for="username">UserName: </label>
        <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password: </label>
        <input type="password" name="password">

        <input type="submit"value="Login">

    </form>

  </div>

{%endblock%}

learning_users/templates/basic_app/registration.html
{%extends "base.html"%}
{%load static%}

{%block body_block%}

  <div class="jumbotron">

    {%if registered%}

      <h1>Thank you for registering!</h1>

    {%else%}

      <h1>아이디 등록이 가능합니다!</h1>
      <h3>아래 양식을 작성해주세요</h3>

      <form enctype="multipart/form-data" method="post">

        {%csrf_token%}
        {{user_form.as_p}}
        {{profile_form.as_p}}

        <input type="submit" value="Register">

      </form>

    {%endif%}

  </div>

{%endblock%}